config = {
    'plot': {
        'time': {
            'fig': 'base_1_2',
            'grid': 'base_1_2',
            'title-sol': 'Solution',
            'title-err': 'Error',
            'label-sol': ['Time', 'Solution'],
            'label-err': ['Time', 'Error'],
            'line-sol-init': ['l1', 'Initial'],
            'line-sol-calc': ['l2', 'Calculated'],
            'line-sol-real': ['l3', 'Analytic'],
            'line-sol-stat': ['l4', 'Stationary'],
            'line-err-real': ['l5', 'Error vs analytic'],
            'line-err-stat': ['l6', 'Error vs stationary'],
        },
        'spatial': {
            'fig': 'base_1_2',
            'grid': 'base_1_2',
            'title-sol': 'Solution',
            'title-err': 'Error',
            'label-sol': ['Point', 'Solution'],
            'label-err': ['Point', 'Error'],
            'line-sol-init': ['l1', 'Initial'],
            'line-sol-calc': ['l2', 'Calculated'],
            'line-sol-real': ['l3', 'Analytic'],
            'line-sol-stat': ['l4', 'Stationary'],
            'line-err-real': ['l5', 'Error vs analytic'],
            'line-err-stat': ['l6', 'Error vs stationary'],
        },
        'conv-time': {
            'fig': 'base_1_3',
            'grid': 'base_1_3',
            'title-err': 'Error vs analytic',
            'title-err-stat': 'Error vs stationary',
            'title-time': 'Computation time',
            'label-err': ['Number of time points', ''],
            'label-err-stat': ['Number of time points', ''],
            'label-time': ['Number of time points', ''],
            'line-real': ['l1', ''],
            'line-appr': ['l2', ''],
            'cols-real': ['#48484c', '#485536', '#8b1d1d', '#5f91ac', '#48484c', '#485536', '#8b1d1d', '#5f91ac'],
            'cols-appr': ['#48484c', '#485536', '#8b1d1d', '#5f91ac', '#48484c', '#485536', '#8b1d1d', '#5f91ac'],
        },
        'conv-spatial': {
            'fig': 'base_1_3',
            'grid': 'base_1_3',
            'title-err': 'Error vs analytic',
            'title-err-stat': 'Error vs stationary',
            'title-time': 'Computation time',
            'label-err': ['Number of spatial points', ''],
            'label-err-stat': ['Number of spatial points', ''],
            'label-time': ['Number of spatial points', ''],
            'line-real': ['l1', ''],
            'line-appr': ['l2', ''],
            'cols-real': ['#48484c', '#485536', '#8b1d1d', '#5f91ac', '#48484c', '#485536', '#8b1d1d', '#5f91ac'],
            'cols-appr': ['#48484c', '#485536', '#8b1d1d', '#5f91ac', '#48484c', '#485536', '#8b1d1d', '#5f91ac'],
        },
    },
    'opts': {
        'plot': {
            'fig': {
                'base_1_2': {
                    'figsize': (10, 5),
                },
                'base_1_3': {
                    'figsize': (12, 5),
                },
            },
            'grid': {
                'base_1_2': {
                    'ncols': 2,
                    'nrows': 1,
                    'left': 0.01,
                    'right': 0.99,
                    'top': 0.99,
                    'bottom': 0.01,
                    'wspace': 0.2,
                    'hspace': 0.1,
                    'width_ratios': [1, 1],
                    'height_ratios': [1],
                },
                'base_1_3': {
                    'ncols': 3,
                    'nrows': 1,
                    'left': 0.,
                    'right': 1.,
                    'top': 1.,
                    'bottom': 0.,
                    'wspace': 0.2,
                    'hspace': 0.,
                    'width_ratios': [1, 1, 1],
                    'height_ratios': [1],
                },
            },
            'line': {
                'l1': {
                    'linestyle': '--',
                    'linewidth': 3,
                    'color': '#48484c',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#48484c',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#48484c',
                },
                'l2': {
                    'linestyle': '-',
                    'linewidth': 1,
                    'color': '#8b1d1d',
                    'marker': 'o',
                    'markersize': 7,
                    'markerfacecolor': '#8b1d1d',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#8b1d1d',
                },
                'l3': {
                    'linestyle': '-',
                    'linewidth': 3,
                    'color': '#485536',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#485536',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#485536',
                },
                'l4': {
                    'linestyle': '-.',
                    'linewidth': 2,
                    'color': '#5f91ac',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#5f91ac',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#5f91ac',
                },
                'l5': {
                    'linestyle': '-',
                    'linewidth': 2,
                    'color': '#485536',
                    'marker': 'o',
                    'markersize': 6,
                    'markerfacecolor': '#8b1d1d',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#8b1d1d',
                },
                'l6': {
                    'linestyle': '-.',
                    'linewidth': 2,
                    'color': '#5f91ac',
                    'marker': '*',
                    'markersize': 6,
                    'markerfacecolor': '#5f91ac',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#5f91ac',
                },
            },
        },
    },
}
