config = {
    'plot': {
        'fig': {
            'base_1_2': {
                'figsize': (10, 5),
            },
        },
        'grid': {
            'base_1_2': {
                'ncols': 2,
                'nrows': 1,
                'left': 0.01,
                'right': 0.99,
                'top': 0.99,
                'bottom': 0.01,
                'wspace': 0.2,
                'hspace': 0.1,
                'width_ratios': [1, 1],
                'height_ratios': [1],
            },
        },
        'line': {
            'init': {
                'linestyle': '--',
                'label': 'Initial',
                'linewidth': 3,
                'color': '#48484c',
                'marker': 'o',
                'markersize': 0,
                'markerfacecolor': '#48484c',
                'markeredgewidth': 0,
                'markeredgecolor': '#48484c',
            },
            'calc': {
                'linestyle': '-',
                'label': 'Calculated',
                'linewidth': 1,
                'color': '#8b1d1d',
                'marker': 'o',
                'markersize': 7,
                'markerfacecolor': '#8b1d1d',
                'markeredgewidth': 1,
                'markeredgecolor': '#8b1d1d',
            },
            'real': {
                'linestyle': '-',
                'label': 'Analytic',
                'linewidth': 3,
                'color': '#485536',
                'marker': 'o',
                'markersize': 0,
                'markerfacecolor': '#485536',
                'markeredgewidth': 0,
                'markeredgecolor': '#485536',
            },
            'stat': {
                'linestyle': '-.',
                'label': 'Stationary',
                'linewidth': 2,
                'color': '#5f91ac',
                'marker': 'o',
                'markersize': 0,
                'markerfacecolor': '#5f91ac',
                'markeredgewidth': 0,
                'markeredgecolor': '#5f91ac',
            },
            'errs': {
                'linestyle': '-',
                'label': 'Error vs analytic',
                'linewidth': 2,
                'color': '#485536',
                'marker': 'o',
                'markersize': 6,
                'markerfacecolor': '#8b1d1d',
                'markeredgewidth': 1,
                'markeredgecolor': '#8b1d1d',
            },
            'errs2': {
                'linestyle': '-.',
                'label': 'Error vs stationary',
                'linewidth': 2,
                'color': '#5f91ac',
                'marker': '*',
                'markersize': 6,
                'markerfacecolor': '#5f91ac',
                'markeredgewidth': 1,
                'markeredgecolor': '#5f91ac',
            },
        },
    },
}
