config = {
    'plot': {
        'time': {
            'fig': 'base_1_2',

            'grid': 'base_1_2',

            'title': 'Solution',
            'label-x': 'Time',
            'label-y': 'Solution',
            'label-init': 'Initial',
            'line-init': 'l1',
            'label-calc': 'Calculated',
            'line-calc': 'l2',
            'label-real': 'Analytic',
            'line-real': 'l3',
            'label-stat': 'Stationary',
            'line-stat': 'l4',

            'title-err': 'Error',
            'label-err-x': 'Time',
            'label-err-y': 'Error',
            'label-err-real': 'Error vs analytic',
            'line-err-real': 'l5',
            'label-err-stat': 'Error vs stationary',
            'line-err-stat': 'l6',
        },
        'spatial': {
            'fig': 'base_1_2',

            'grid': 'base_1_2',

            'title': 'Solution',
            'label-x': 'Time',
            'label-y': 'Point',
            'label-init': 'Initial',
            'line-init': 'l1',
            'label-calc': 'Calculated',
            'line-calc': 'l2',
            'label-real': 'Analytic',
            'line-real': 'l3',
            'label-stat': 'Stationary',
            'line-stat': 'l4',

            'title-err': 'Error',
            'label-err-x': 'Point',
            'label-err-y': 'Error',
            'label-err-real': 'Error vs analytic',
            'line-err-real': 'l5',
            'label-err-stat': 'Error vs stationary',
            'line-err-stat': 'l6',
        },
    },
    'opts': {
        'plot': {
            'fig': {
                'base_1_2': {
                    'figsize': (10, 5),
                },
            },
            'grid': {
                'base_1_2': {
                    'ncols': 2,
                    'nrows': 1,
                    'left': 0.01,
                    'right': 0.99,
                    'top': 0.99,
                    'bottom': 0.01,
                    'wspace': 0.2,
                    'hspace': 0.1,
                    'width_ratios': [1, 1],
                    'height_ratios': [1],
                },
            },
            'line': {
                'l1': {
                    'linestyle': '--',
                    'linewidth': 3,
                    'color': '#48484c',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#48484c',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#48484c',
                },
                'l2': {
                    'linestyle': '-',
                    'linewidth': 1,
                    'color': '#8b1d1d',
                    'marker': 'o',
                    'markersize': 7,
                    'markerfacecolor': '#8b1d1d',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#8b1d1d',
                },
                'l3': {
                    'linestyle': '-',
                    'linewidth': 3,
                    'color': '#485536',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#485536',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#485536',
                },
                'l4': {
                    'linestyle': '-.',
                    'linewidth': 2,
                    'color': '#5f91ac',
                    'marker': 'o',
                    'markersize': 0,
                    'markerfacecolor': '#5f91ac',
                    'markeredgewidth': 0,
                    'markeredgecolor': '#5f91ac',
                },
                'l5': {
                    'linestyle': '-',
                    'linewidth': 2,
                    'color': '#485536',
                    'marker': 'o',
                    'markersize': 6,
                    'markerfacecolor': '#8b1d1d',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#8b1d1d',
                },
                'l6': {
                    'linestyle': '-.',
                    'linewidth': 2,
                    'color': '#5f91ac',
                    'marker': '*',
                    'markersize': 6,
                    'markerfacecolor': '#5f91ac',
                    'markeredgewidth': 1,
                    'markeredgecolor': '#5f91ac',
                },
            },
        },
    },
}
